name: uxarray-release-testing
channels:
  - conda-forge
  - anissa111
  - ncar
dependencies:
  - python
  - matplotlib
  - jupyterlab>=3
  - geocat-comp
  - xarray
  - ipywidgets
  - dask
  - netcdf4
  - line_profiler
  - intake-esm
  - ncar-jobqueue
  - memory_profiler
  - uxarray
    