name: geocat-testing
channels:
  - conda-forge
  - ncar
dependencies:
  - python
  - matplotlib
  - jupyterlab>=3
  - geocat-comp
  - xarray
  - ipywidgets
  - dask
  - netcdf4
  - line_profiler
  - intake-esm
  - ncar-jobqueue
  - pip
  - pip:
    - git+https://github.com/UXARRAY/uxarray@main